In [137]:
import tensorflow as tf 
import matplotlib as plt
import pandas as pd 
import seaborn as sns

In [138]:
import tensorflow as tf 
training_set = tf.keras.utils.image_dataset_from_directory(
    'C:\\Users\\GEETHANJALICHARVI\\OneDrive\\Documents\\oral cancer copy\\Oral Cancer\\Oral Cancer Dataset\\train',  # Path to your training directory
    labels="inferred",
    label_mode="categorical",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=42
)


Found 661 files belonging to 2 classes.


In [139]:
import tensorflow as tf

training_set = tf.keras.utils.image_dataset_from_directory(
    'C:\\Users\\GEETHANJALICHARVI\\OneDrive\\Documents\\oral cancer copy\\Oral Cancer\\Oral Cancer Dataset\\train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False
)


Found 661 files belonging to 2 classes.


In [140]:
import os

path = r"C:\Users\GEETHANJALICHARVI\OneDrive\Documents\oral cancer copy\Oral Cancer\Oral Cancer Dataset"
print(os.listdir(path))


['test', 'train', 'valid']


In [141]:
import os

parent_path = r"C:\Users\GEETHANJALICHARVI\OneDrive\Documents\oral cancer copy\Oral Cancer\Oral Cancer Dataset"
print("Parent directory exists:", os.path.exists(parent_path))
if os.path.exists(parent_path):
    print("Contents of the parent directory:", os.listdir(parent_path))


Parent directory exists: True
Contents of the parent directory: ['test', 'train', 'valid']


In [142]:
import tensorflow as tf

training_set = tf.keras.utils.image_dataset_from_directory(
    'C:\\Users\\GEETHANJALICHARVI\\OneDrive\\Documents\\oral cancer copy\\Oral Cancer\\Oral Cancer Dataset\\train',  # Path to your training directory
    labels="inferred",  # Automatically infer the labels from folder names
    label_mode="categorical",  # Labels will be one-hot encoded
    batch_size=32,
    image_size=(128, 128),  # Resize images to 128x128
    shuffle=True,  # Shuffle the dataset
    seed=42,  # Set random seed for reproducibility
    interpolation="bilinear"  # Image interpolation method
)

print("Training dataset loaded successfully.")


Found 661 files belonging to 2 classes.
Training dataset loaded successfully.


In [143]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 2), dtype=tf.float32, name=None))>

In [144]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(rescale=1./255)

# Load the training dataset
training_set = datagen.flow_from_directory(
    'C:\\Users\\GEETHANJALICHARVI\\OneDrive\\Documents\\oral cancer copy\\Oral Cancer\\Oral Cancer Dataset\\train',
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical'
)

# Load the validation dataset
validation_set = datagen.flow_from_directory(
    'C:\\Users\\GEETHANJALICHARVI\\OneDrive\\Documents\\oral cancer copy\\Oral Cancer\\Oral Cancer Dataset\\valid',
    target_size=(128, 128),
    batch_size=32,
    class_mode='categorical'
)


Found 661 images belonging to 2 classes.
Found 950 images belonging to 2 classes.


In [145]:
import os

# Path to your training directory
path = r'C:\\Users\\GEETHANJALICHARVI\\OneDrive\\Documents\\oral cancer copy\\Oral Cancer\\Oral Cancer Dataset\\train'

# List files in the directory
files = os.listdir(path)
print(f"Files in directory: {files}")


Files in directory: ['class1', 'class2']


In [146]:
training_set

In [147]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

[[[[0.6901961  0.5137255  0.6666667 ]
   [0.7137255  0.5568628  0.7019608 ]
   [0.75294125 0.6156863  0.7725491 ]
   ...
   [0.64705884 0.43529415 0.49803925]
   [0.6509804  0.43921572 0.5019608 ]
   [0.6509804  0.43529415 0.50980395]]

  [[0.75294125 0.63529414 0.77647066]
   [0.7725491  0.654902   0.7960785 ]
   [0.7843138  0.68235296 0.8352942 ]
   ...
   [0.6666667  0.454902   0.5176471 ]
   [0.6627451  0.45098042 0.5137255 ]
   [0.6745098  0.46274513 0.5254902 ]]

  [[0.79215693 0.7058824  0.8588236 ]
   [0.80392164 0.7176471  0.8705883 ]
   [0.8078432  0.72156864 0.8745099 ]
   ...
   [0.654902   0.43137258 0.49803925]
   [0.67058825 0.43921572 0.50980395]
   [0.6745098  0.4431373  0.5137255 ]]

  ...

  [[0.29411766 0.36078432 0.57254905]
   [0.29803923 0.36078432 0.5647059 ]
   [0.30588236 0.35686275 0.56078434]
   ...
   [0.40000004 0.33333334 0.40784317]
   [0.3921569  0.31764707 0.3921569 ]
   [0.3019608  0.2627451  0.35686275]]

  [[0.3137255  0.3647059  0.5686275 ]
   [0.3

In [148]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential 

In [149]:
model = Sequential()

In [150]:
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

# Your model code
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape=(128, 128,3)))
model.add(Conv2D(filters=32, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [151]:
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

# Your model code
model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu', input_shape=(128, 128, 3)))
model.add(Conv2D(filters=64, kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [152]:
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

# Your model code
model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu', input_shape=(128, 128, 3)))
model.add(Conv2D(filters=128, kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [153]:
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

# Your model code
model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu', input_shape=(128, 128, 3)))
model.add(Conv2D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [154]:
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

# Your model code
model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu', input_shape=(128, 128, 3)))
model.add(Conv2D(filters=512, kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [155]:
model.add(Dropout(0.25)) #avoid overfitting

In [156]:
model.add(Flatten())


In [157]:
model.add(Dense(units=1500, activation='relu'))

In [158]:
model.add(Dropout(0.4))

In [159]:
#output layer 
model.add(Dense(units=38,activation='softmax'))

In [160]:
model.compile(optimizer=tf.keras.optimizers.legacy.Adam(
    learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])


In [161]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_50 (Conv2D)          (None, 128, 128, 32)      896       
                                                                 
 conv2d_51 (Conv2D)          (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d_25 (MaxPoolin  (None, 63, 63, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_52 (Conv2D)          (None, 63, 63, 64)        18496     
                                                                 
 conv2d_53 (Conv2D)          (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_26 (MaxPoolin  (None, 30, 30, 64)       0         
 g2D)                                                

In [162]:
tf.keras.layers.Dense(2, activation='softmax')


In [163]:
import tensorflow as tf

# Number of classes (ensure this matches your dataset)
num_classes = 2 

def preprocess_labels(labels):
    labels = tf.one_hot(labels, depth=num_classes)  # Ensure one-hot encoding
    return labels

# Example labels (can be single or batch)
labels = tf.constant([0, 1])  # Batch of labels

# Process labels
processed_labels = preprocess_labels(labels)

# Convert TensorFlow tensor to NumPy array and print
print(processed_labels.numpy())


[[1. 0.]
 [0. 1.]]


In [164]:
training_history =  model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10


InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
      app.launch_new_instance()
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
      app.start()
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\kernelapp.py", line 739, in start
      self.io_loop.start()
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\tornado\platform\asyncio.py", line 205, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\asyncio\base_events.py", line 603, in run_forever
      self._run_once()
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\asyncio\base_events.py", line 1909, in _run_once
      handle._run()
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
      await self.process_one()
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
      await dispatch(*args)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
      await result
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
      await super().execute_request(stream, ident, parent)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
      reply_content = await reply_content
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
      res = shell.run_cell(
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
      result = self._run_cell(
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
      result = runner(coro)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\GEETHANJALICHARVI\AppData\Local\Temp\ipykernel_17708\3270507978.py", line 1, in <module>
      training_history =  model.fit(x=training_set,validation_data=validation_set,epochs=10)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\training.py", line 994, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\training.py", line 1052, in compute_loss
      return self.compiled_loss(
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\losses.py", line 152, in __call__
      losses = call_fn(y_true, y_pred)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\losses.py", line 272, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\losses.py", line 1990, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "c:\Users\GEETHANJALICHARVI\anaconda3\envs\tensorflow_env\lib\site-packages\keras\backend.py", line 5535, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[32,38] labels_size=[32,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_8248]

In [165]:
model.add(Dense(num_classes, activation='softmax'))  # Ensure num_classes is correct
